/*================================================================================*/
/* DDL SCRIPT                                                                     */
/*================================================================================*/
/*  Title    : Enarksh                                                            */
/*  FileName : enarksh.ecm                                                        */
/*  Platform : MySQL 5                                                            */
/*  Version  : Concept                                                            */
/*  Date     : donderdag 4 juni 2015                                              */
/*================================================================================*/
/*================================================================================*/
/* CREATE TABLES                                                                  */
/*================================================================================*/

CREATE TABLE `AUT_USER` (
  `usr_login` VARCHAR(32) NOT NULL,
  `usr_email` VARCHAR(80) NOT NULL,
  `usr_role_operator` BOOL NOT NULL,
  `usr_role_admin` BOOL NOT NULL,
  CONSTRAINT `PK_AUT_USER` PRIMARY KEY (`usr_login`)
)
engine=innodb;

CREATE TABLE `ENK_BLOB_DATA` (
  `bdt_id` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `bdt_inserted` DATETIME NOT NULL,
  `bdt_crc32` INT UNSIGNED NOT NULL,
  `bdt_size` INT UNSIGNED NOT NULL,
  `bdt_mime_type` VARCHAR(48) NOT NULL,
  `bdt_data` LONGBLOB NOT NULL,
  CONSTRAINT `PK_ENK_BLOB_DATA` PRIMARY KEY (`bdt_id`)
)
engine=innodb;

CREATE TABLE `ENK_BLOB` (
  `blb_id` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `bdt_id` INT UNSIGNED NOT NULL,
  `blb_inserted` DATETIME NOT NULL,
  `blb_crc32` INT UNSIGNED NOT NULL,
  `blb_filename` VARCHAR(255) NOT NULL,
  `blb_mime_type` VARCHAR(48) NOT NULL,
  `blb_size` INT UNSIGNED NOT NULL,
  CONSTRAINT `PK_ENK_BLOB` PRIMARY KEY (`blb_id`)
)
engine=innodb;

CREATE TABLE `ENK_URI` (
  `uri_id` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `uri_crc32` INT UNSIGNED NOT NULL,
  `uri_uri` VARCHAR(4000) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  CONSTRAINT `PK_ENK_URI` PRIMARY KEY (`uri_id`)
)
engine=innodb;

CREATE TABLE `ENK_SCHEDULE` (
  `sch_id` SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
  `sch_name` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  CONSTRAINT `PK_ENK_SCHEDULE` PRIMARY KEY (`sch_id`)
)
engine=innodb;

CREATE TABLE `ENK_SCHEDULE_REVISION` (
  `srv_id` SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
  `blb_id` INT UNSIGNED NOT NULL,
  `sch_id` SMALLINT UNSIGNED NOT NULL,
  `srv_number` TINYINT UNSIGNED NOT NULL,
  `srv_current` BOOL DEFAULT false NOT NULL,
  CONSTRAINT `IX_ENK_SCHEDULE_REVISION1` PRIMARY KEY (`srv_id`)
)
engine=innodb;

CREATE TABLE `ENK_NODE_TYPE` (
  `ntp_id` SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
  `ntp_name` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `ntp_label` VARCHAR(40) CHARACTER SET ascii,
  CONSTRAINT `PK_ENK_NODE_TYPE` PRIMARY KEY (`ntp_id`)
)
engine=innodb;

CREATE TABLE `ENK_NODE` (
  `nod_id` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `nod_id_parent` INT UNSIGNED,
  `ntp_id` SMALLINT UNSIGNED NOT NULL,
  `srv_id` SMALLINT UNSIGNED NOT NULL,
  `uri_id` INT UNSIGNED NOT NULL,
  `nod_name` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `nod_recursion_level` INT NOT NULL,
  `nod_dependency_level` INT NOT NULL,
  `nod_user_name` VARCHAR(32),
  `nod_command` VARCHAR(1000),
  `nod_master` BOOL NOT NULL,
  CONSTRAINT `PK_ENK_NODE` PRIMARY KEY (`nod_id`)
)
engine=innodb;

CREATE TABLE `ENK_HOST` (
  `hst_id` SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
  `hst_name` VARCHAR(64) NOT NULL,
  CONSTRAINT `PK_ENK_HOST` PRIMARY KEY (`hst_id`)
)
engine=innodb;

CREATE TABLE `ENK_RW_STATUS` (
  `rws_id` TINYINT UNSIGNED AUTO_INCREMENT NOT NULL,
  `rws_name` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `rws_label` VARCHAR(40) CHARACTER SET ascii NOT NULL,
  CONSTRAINT `PK_ENK_RW_STATUS` PRIMARY KEY (`rws_id`)
)
engine=innodb;

CREATE TABLE `ENK_RESOURCE_TYPE` (
  `rtp_id` TINYINT UNSIGNED AUTO_INCREMENT NOT NULL,
  `rtp_name` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `rtp_label` VARCHAR(40) CHARACTER SET ascii NOT NULL,
  CONSTRAINT `PK_ENK_RESOURCE_TYPE` PRIMARY KEY (`rtp_id`)
)
engine=innodb;

CREATE TABLE `ENK_RESOURCE` (
  `rsc_id` INT AUTO_INCREMENT NOT NULL,
  `hst_id` SMALLINT UNSIGNED,
  `nod_id` INT UNSIGNED,
  `rtp_id` TINYINT UNSIGNED NOT NULL,
  `rws_id_consumpted` TINYINT UNSIGNED,
  `uri_id` INT UNSIGNED NOT NULL,
  `rsc_name` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `rsc_amount` BIGINT,
  `rsc_amount_consumpted` BIGINT,
  CONSTRAINT `PK_ENK_RESOURCE` PRIMARY KEY (`rsc_id`)
)
engine=innodb;

/*
COMMENT ON COLUMN `ENK_RESOURCE`.`rsc_amount_consumpted`
The amount consumpted by currently running nodes.
*/

CREATE TABLE `ENK_CONSUMPTION_TYPE` (
  `ctp_id` TINYINT UNSIGNED AUTO_INCREMENT NOT NULL,
  `ctp_name` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `ctp_label` VARCHAR(40) CHARACTER SET ascii,
  CONSTRAINT `PK_ENK_CONSUMPTION_TYPE` PRIMARY KEY (`ctp_id`)
)
engine=innodb;

CREATE TABLE `ENK_CONSUMPTION` (
  `cns_id` INT AUTO_INCREMENT NOT NULL,
  `ctp_id` TINYINT UNSIGNED NOT NULL,
  `nod_id` INT UNSIGNED NOT NULL,
  `rsc_id` INT NOT NULL,
  `rws_id` TINYINT UNSIGNED,
  `uri_id` INT UNSIGNED NOT NULL,
  `cns_amount` BIGINT,
  CONSTRAINT `PK_ENK_CONSUMPTION` PRIMARY KEY (`cns_id`)
)
engine=innodb;

CREATE TABLE `ENK_PORT_TYPE` (
  `ptt_id` TINYINT UNSIGNED AUTO_INCREMENT NOT NULL,
  `ptt_label` VARCHAR(40) CHARACTER SET ascii,
  CONSTRAINT `PK_ENK_PORT_TYPE` PRIMARY KEY (`ptt_id`)
)
engine=innodb;

CREATE TABLE `ENK_PORT` (
  `prt_id` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `nod_id` INT UNSIGNED NOT NULL,
  `ptt_id` TINYINT UNSIGNED NOT NULL,
  `uri_id` INT UNSIGNED NOT NULL,
  `prt_name` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  CONSTRAINT `PK_ENK_PORT` PRIMARY KEY (`prt_id`)
)
engine=innodb;

CREATE TABLE `ENK_DEPENDENCY` (
  `prt_id_predecessor` INT UNSIGNED NOT NULL,
  `prt_id_dependant` INT UNSIGNED NOT NULL,
  CONSTRAINT `PK_ENK_DEPENDENCY` PRIMARY KEY (`prt_id_predecessor`, `prt_id_dependant`)
)
engine=innodb;

CREATE TABLE `ENK_ERROR` (
  `err_id` SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
  `err_description` VARCHAR(40) NOT NULL,
  `err_label` VARCHAR(40) CHARACTER SET ascii NOT NULL,
  CONSTRAINT `PK_ENK_ERROR` PRIMARY KEY (`err_id`)
)
engine=innodb;

CREATE TABLE `ENK_RUN` (
  `run_id` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `srv_id` SMALLINT UNSIGNED NOT NULL,
  `run_current` BOOL NOT NULL,
  `run_datetime_start` DATETIME,
  `run_datetime_stop` DATETIME,
  CONSTRAINT `PK_ENK_RUN` PRIMARY KEY (`run_id`)
)
engine=innodb;

CREATE TABLE `ENK_RUN_STATUS` (
  `rst_id` TINYINT UNSIGNED AUTO_INCREMENT NOT NULL,
  `rst_name` VARCHAR(40) NOT NULL,
  `rst_weight` TINYINT NOT NULL,
  `rst_label` VARCHAR(40) CHARACTER SET ascii,
  CONSTRAINT `PK_ENK_RUN_STATUS` PRIMARY KEY (`rst_id`)
)
engine=innodb;

CREATE TABLE `ENK_RUN_NODE` (
  `rnd_id` INT AUTO_INCREMENT NOT NULL,
  `blb_id_err` INT UNSIGNED,
  `blb_id_log` INT UNSIGNED,
  `nod_id` INT UNSIGNED NOT NULL,
  `rst_id` TINYINT UNSIGNED NOT NULL,
  `run_id` INT UNSIGNED NOT NULL,
  `rnd_current` BOOL NOT NULL,
  `rnd_datetime_start` DATETIME,
  `rnd_datetime_stop` DATETIME,
  `rnd_duration` INT UNSIGNED,
  `rnd_exit_status` INT,
  `rnd_size_log` BIGINT UNSIGNED,
  `rnd_size_err` BIGINT UNSIGNED,
  CONSTRAINT `PK_ENK_RUN_NODE` PRIMARY KEY (`rnd_id`)
);

CREATE TABLE `ENK_RUN_NODE_STATUS_CHANGE` (
  `nsc_id` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `rnd_id` INT NOT NULL,
  `rnd_id_old` INT,
  `run_id` INT UNSIGNED NOT NULL,
  `rst_id` TINYINT UNSIGNED NOT NULL,
  CONSTRAINT `PK_ENK_RUN_NODE_STATUS_CHANGE` PRIMARY KEY (`nsc_id`)
)
engine=innodb;

CREATE TABLE `ENK_SCHEDULE_REVISION_ADDENDUM` (
  `srv_id` SMALLINT UNSIGNED NOT NULL,
  `nod_id_activate` INT UNSIGNED NOT NULL,
  `nod_id_arrest` INT UNSIGNED NOT NULL,
  `nod_id_schedule` INT UNSIGNED NOT NULL,
  CONSTRAINT `PK_ENK_SCHEDULE_REVISION_ADDENDUM` PRIMARY KEY (`srv_id`)
)
engine=innodb;

/*================================================================================*/
/* CREATE INDEXES                                                                 */
/*================================================================================*/

CREATE INDEX `IX_ENK_BLOB_DATA1` ON `ENK_BLOB_DATA` (`bdt_crc32`);

CREATE INDEX `IX_ENK_BLOB1` ON `ENK_BLOB` (`bdt_id`);

CREATE INDEX `IX_ENK_URI1` ON `ENK_URI` (`uri_uri`(50));

CREATE INDEX `IX_ENK_URI2` ON `ENK_URI` (`uri_crc32`);

CREATE UNIQUE INDEX `IX_ENK_SCHEDULE_REVISION2` ON `ENK_SCHEDULE_REVISION` (`sch_id`, `srv_number`);

CREATE INDEX `IX_ENK_SCHEDULE_REVISION3` ON `ENK_SCHEDULE_REVISION` (`blb_id`);

CREATE INDEX `IX_ENK_NODE2` ON `ENK_NODE` (`uri_id`);

CREATE INDEX `IX_ENK_NODE3` ON `ENK_NODE` (`nod_id_parent`);

CREATE INDEX `IX_ENK_NODE4` ON `ENK_NODE` (`srv_id`);

CREATE INDEX `IX_ENK_NODE5` ON `ENK_NODE` (`ntp_id`);

CREATE UNIQUE INDEX `IX_ENK_RESOURCE1` ON `ENK_RESOURCE` (`nod_id`, `rsc_name`);

CREATE INDEX `IX_ENK_RESOURCE3` ON `ENK_RESOURCE` (`nod_id`);

CREATE INDEX `IX_ENK_RESOURCE4` ON `ENK_RESOURCE` (`rws_id_consumpted`);

CREATE INDEX `IX_ENK_RESOURCE5` ON `ENK_RESOURCE` (`rtp_id`);

CREATE INDEX `IX_ENK_RESOURCE6` ON `ENK_RESOURCE` (`hst_id`);

CREATE INDEX `IX_ENK_RESOURCE7` ON `ENK_RESOURCE` (`uri_id`);

CREATE INDEX `IX_ENK_CONSUMPTION2` ON `ENK_CONSUMPTION` (`nod_id`);

CREATE INDEX `IX_ENK_CONSUMPTION3` ON `ENK_CONSUMPTION` (`uri_id`);

CREATE INDEX `IX_ENK_CONSUMPTION4` ON `ENK_CONSUMPTION` (`rsc_id`);

CREATE INDEX `IX_ENK_CONSUMPTION5` ON `ENK_CONSUMPTION` (`ctp_id`);

CREATE INDEX `IX_ENK_CONSUMPTION6` ON `ENK_CONSUMPTION` (`rws_id`);

CREATE INDEX `IX_ENK_PORT1` ON `ENK_PORT` (`nod_id`);

CREATE UNIQUE INDEX `IX_ENK_DEPENDENCY1` ON `ENK_DEPENDENCY` (`prt_id_dependant`, `prt_id_predecessor`);

CREATE INDEX `IX_ENK_RUN_NODE1` ON `ENK_RUN_NODE` (`nod_id`);

CREATE INDEX `IX_ENK_RUN_NODE2` ON `ENK_RUN_NODE` (`run_id`);

CREATE INDEX `IX_ENK_RUN_NODE3` ON `ENK_RUN_NODE` (`rst_id`);

CREATE INDEX `IX_ENK_RUN_NODE4` ON `ENK_RUN_NODE` (`blb_id_log`);

CREATE INDEX `IX_ENK_RUN_NODE5` ON `ENK_RUN_NODE` (`blb_id_err`);

CREATE INDEX `IX_ENK_RUN_NODE_STATUS_CHANGE1` ON `ENK_RUN_NODE_STATUS_CHANGE` (`rnd_id_old`);

CREATE INDEX `IX_ENK_RUN_NODE_STATUS_CHANGE2` ON `ENK_RUN_NODE_STATUS_CHANGE` (`run_id`);

CREATE INDEX `IX_ENK_RUN_NODE_STATUS_CHANGE3` ON `ENK_RUN_NODE_STATUS_CHANGE` (`rnd_id`);

CREATE INDEX `IX_ENK_SCHEDULE_REVISION_ADDENDUM1` ON `ENK_SCHEDULE_REVISION_ADDENDUM` (`srv_id`);

CREATE INDEX `IX_ENK_SCHEDULE_REVISION_ADDENDUM5` ON `ENK_SCHEDULE_REVISION_ADDENDUM` (`nod_id_activate`);

CREATE INDEX `IX_ENK_SCHEDULE_REVISION_ADDENDUM6` ON `ENK_SCHEDULE_REVISION_ADDENDUM` (`nod_id_schedule`);

CREATE INDEX `IX_ENK_SCHEDULE_REVISION_ADDENDUM7` ON `ENK_SCHEDULE_REVISION_ADDENDUM` (`nod_id_arrest`);

/*================================================================================*/
/* CREATE FOREIGN KEYS                                                            */
/*================================================================================*/

ALTER TABLE `ENK_BLOB`
  ADD CONSTRAINT `FK_ENK_BLOB_ENK_BLOB_DATA`
  FOREIGN KEY (`bdt_id`) REFERENCES `ENK_BLOB_DATA` (`bdt_id`);

ALTER TABLE `ENK_SCHEDULE_REVISION`
  ADD CONSTRAINT `FK_ENK_SCHEDULE_REVISION_ENK_SCHEDULE`
  FOREIGN KEY (`sch_id`) REFERENCES `ENK_SCHEDULE` (`sch_id`);

ALTER TABLE `ENK_SCHEDULE_REVISION`
  ADD CONSTRAINT `FK_ENK_SCHEDULE_REVISION_ENK_BLOB`
  FOREIGN KEY (`blb_id`) REFERENCES `ENK_BLOB` (`blb_id`);

ALTER TABLE `ENK_NODE`
  ADD CONSTRAINT `FK_ENK_RUN_NODE_ENK_URI`
  FOREIGN KEY (`uri_id`) REFERENCES `ENK_URI` (`uri_id`);

ALTER TABLE `ENK_NODE`
  ADD CONSTRAINT `FK_ENK_RUN_NODE_ENK_RUN_NODE`
  FOREIGN KEY (`nod_id_parent`) REFERENCES `ENK_NODE` (`nod_id`);

ALTER TABLE `ENK_NODE`
  ADD CONSTRAINT `FK_ENK_RUN_NODE_ENK_SCHEDULE_REVISION`
  FOREIGN KEY (`srv_id`) REFERENCES `ENK_SCHEDULE_REVISION` (`srv_id`);

ALTER TABLE `ENK_NODE`
  ADD CONSTRAINT `FK_ENK_RUN_NODE_ENK_NODE_TYPE`
  FOREIGN KEY (`ntp_id`) REFERENCES `ENK_NODE_TYPE` (`ntp_id`);

ALTER TABLE `ENK_RESOURCE`
  ADD CONSTRAINT `FK_ENK_RUN_RESOURCE_ENK_RUN_NODE`
  FOREIGN KEY (`nod_id`) REFERENCES `ENK_NODE` (`nod_id`);

ALTER TABLE `ENK_RESOURCE`
  ADD CONSTRAINT `FK_ENK_RUN_RESOURCE_ENK_RW_STATUS`
  FOREIGN KEY (`rws_id_consumpted`) REFERENCES `ENK_RW_STATUS` (`rws_id`);

ALTER TABLE `ENK_RESOURCE`
  ADD CONSTRAINT `FK_ENK_RUN_RESOURCE_ENK_RESOURCE_TYPE`
  FOREIGN KEY (`rtp_id`) REFERENCES `ENK_RESOURCE_TYPE` (`rtp_id`);

ALTER TABLE `ENK_RESOURCE`
  ADD CONSTRAINT `FK_ENK_RUN_RESOURCE_ENK_HOST`
  FOREIGN KEY (`hst_id`) REFERENCES `ENK_HOST` (`hst_id`);

ALTER TABLE `ENK_RESOURCE`
  ADD CONSTRAINT `FK_ENK_RUN_RESOURCE_ENK_URI`
  FOREIGN KEY (`uri_id`) REFERENCES `ENK_URI` (`uri_id`);

ALTER TABLE `ENK_CONSUMPTION`
  ADD CONSTRAINT `FK_ENK_CONSUMPTION2_ENK_RUN_NODE`
  FOREIGN KEY (`nod_id`) REFERENCES `ENK_NODE` (`nod_id`);

ALTER TABLE `ENK_CONSUMPTION`
  ADD CONSTRAINT `FK_ENK_CONSUMPTION2_ENK_URI`
  FOREIGN KEY (`uri_id`) REFERENCES `ENK_URI` (`uri_id`);

ALTER TABLE `ENK_CONSUMPTION`
  ADD CONSTRAINT `FK_ENK_CONSUMPTION2_ENK_RUN_RESOURCE`
  FOREIGN KEY (`rsc_id`) REFERENCES `ENK_RESOURCE` (`rsc_id`);

ALTER TABLE `ENK_CONSUMPTION`
  ADD CONSTRAINT `FK_ENK_RUN_CONSUMPTION_ENK_CONSUMPTION_TYPE`
  FOREIGN KEY (`ctp_id`) REFERENCES `ENK_CONSUMPTION_TYPE` (`ctp_id`);

ALTER TABLE `ENK_CONSUMPTION`
  ADD CONSTRAINT `FK_ENK_RUN_CONSUMPTION_ENK_RW_STATUS`
  FOREIGN KEY (`rws_id`) REFERENCES `ENK_RW_STATUS` (`rws_id`);

ALTER TABLE `ENK_PORT`
  ADD CONSTRAINT `FK_ENK_PORT_ENK_PORT_TYPE`
  FOREIGN KEY (`ptt_id`) REFERENCES `ENK_PORT_TYPE` (`ptt_id`);

ALTER TABLE `ENK_PORT`
  ADD CONSTRAINT `FK_ENK_PORT_ENK_URI`
  FOREIGN KEY (`uri_id`) REFERENCES `ENK_URI` (`uri_id`);

ALTER TABLE `ENK_PORT`
  ADD CONSTRAINT `FK_ENK_PORT_ENK_RUN_NODE`
  FOREIGN KEY (`nod_id`) REFERENCES `ENK_NODE` (`nod_id`);

ALTER TABLE `ENK_DEPENDENCY`
  ADD CONSTRAINT `FK_ENK_DEPENDENCY_ENK_PORT2`
  FOREIGN KEY (`prt_id_dependant`) REFERENCES `ENK_PORT` (`prt_id`);

ALTER TABLE `ENK_DEPENDENCY`
  ADD CONSTRAINT `FK_ENK_DEPENDENCY_ENK_PORT`
  FOREIGN KEY (`prt_id_dependant`) REFERENCES `ENK_PORT` (`prt_id`);

ALTER TABLE `ENK_RUN`
  ADD CONSTRAINT `FK_ENK_RUN_ENK_SCHEDULE_REVISION`
  FOREIGN KEY (`srv_id`) REFERENCES `ENK_SCHEDULE_REVISION` (`srv_id`);

ALTER TABLE `ENK_RUN_NODE`
  ADD CONSTRAINT `FK_ENK_RUN_NODE_ENK_NODE`
  FOREIGN KEY (`nod_id`) REFERENCES `ENK_NODE` (`nod_id`);

ALTER TABLE `ENK_RUN_NODE`
  ADD CONSTRAINT `FK_ENK_RUN_NODE_ENK_RUN2`
  FOREIGN KEY (`run_id`) REFERENCES `ENK_RUN` (`run_id`);

ALTER TABLE `ENK_RUN_NODE`
  ADD CONSTRAINT `FK_ENK_RUN_NODE_ENK_RUN_STATUS2`
  FOREIGN KEY (`rst_id`) REFERENCES `ENK_RUN_STATUS` (`rst_id`);

ALTER TABLE `ENK_RUN_NODE`
  ADD CONSTRAINT `FK_ENK_RUN_NODE_ENK_BLOB2`
  FOREIGN KEY (`blb_id_log`) REFERENCES `ENK_BLOB` (`blb_id`);

ALTER TABLE `ENK_RUN_NODE`
  ADD CONSTRAINT `FK_ENK_RUN_NODE_ENK_BLOB`
  FOREIGN KEY (`blb_id_err`) REFERENCES `ENK_BLOB` (`blb_id`);

ALTER TABLE `ENK_RUN_NODE_STATUS_CHANGE`
  ADD CONSTRAINT `FK_NEW_TABLE_ENK_RUN`
  FOREIGN KEY (`run_id`) REFERENCES `ENK_RUN` (`run_id`);

ALTER TABLE `ENK_RUN_NODE_STATUS_CHANGE`
  ADD CONSTRAINT `FK_NEW_TABLE_ENK_RUN_STATUS`
  FOREIGN KEY (`rst_id`) REFERENCES `ENK_RUN_STATUS` (`rst_id`);

ALTER TABLE `ENK_RUN_NODE_STATUS_CHANGE`
  ADD CONSTRAINT `FK_ENK_NODE_STATUS_CHANGE_ENK_RUN_NODE`
  FOREIGN KEY (`rnd_id_old`) REFERENCES `ENK_RUN_NODE` (`rnd_id`);

ALTER TABLE `ENK_RUN_NODE_STATUS_CHANGE`
  ADD CONSTRAINT `FK_ENK_NODE_STATUS_CHANGE_ENK_RUN_NODE2`
  FOREIGN KEY (`rnd_id`) REFERENCES `ENK_RUN_NODE` (`rnd_id`);

ALTER TABLE `ENK_SCHEDULE_REVISION_ADDENDUM`
  ADD CONSTRAINT `FK_ENK_SCHEDULE_REVISION_ADDENDUM_ENK_SCHEDULE_REVISION`
  FOREIGN KEY (`srv_id`) REFERENCES `ENK_SCHEDULE_REVISION` (`srv_id`);

ALTER TABLE `ENK_SCHEDULE_REVISION_ADDENDUM`
  ADD CONSTRAINT `FK_ENK_SCHEDULE_REVISION_ADDENDUM_ENK_RUN_NODE`
  FOREIGN KEY (`nod_id_activate`) REFERENCES `ENK_NODE` (`nod_id`);

ALTER TABLE `ENK_SCHEDULE_REVISION_ADDENDUM`
  ADD CONSTRAINT `FK_ENK_SCHEDULE_REVISION_ADDENDUM_ENK_RUN_NODE2`
  FOREIGN KEY (`nod_id_schedule`) REFERENCES `ENK_NODE` (`nod_id`);

ALTER TABLE `ENK_SCHEDULE_REVISION_ADDENDUM`
  ADD CONSTRAINT `FK_ENK_SCHEDULE_REVISION_ADDENDUM_ENK_RUN_NODE3`
  FOREIGN KEY (`nod_id_arrest`) REFERENCES `ENK_NODE` (`nod_id`);
