#!/bin/bash
#
# chkconfig: 35 90 10
# description: Enarksh - A concurrent scheduler.
# config: /opt/enarksh/etc/config.php
# config: /opt/enarksh/etc/allowed_users

#
# Get functions from functions library
. /etc/init.d/functions

ENK_HOME=/opt/enarksh
LOCKFILE=/var/lock/subsys/enarksh

# Start the service Enarksh
start()
{
	if [ ! -f "$LOCKFILE" ]; then
		rm -f "$ENK_HOME/var/lock/loggerd.pid"
		rm -f "$ENK_HOME/var/lock/spawnerd.pid"
		rm -f "$ENK_HOME/var/lock/controllerd.pid"

		echo -n "Starting Enarksh logger: "
		daemon --user enarksh "$ENK_HOME/bin/loggerd logger -d"
		success $"Enarksh loggerd startup"
		echo

		echo -n "Starting Enarksh spawner: "
		daemon "$ENK_HOME/bin/spawnerd spawner -d"
		success $"Enarksh spawnerd startup"
		echo

		echo -n "Starting Enarksh controller: "
		daemon --user enarksh "$ENK_HOME/bin/controllerd controller -d"
		success $"Enarksh controllerd startup" &
		echo

		touch "$LOCKFILE"
	fi
}

# Restart the service Enarksh
stop()
{
	echo -n "Stopping Enarksh controller: "
	killproc -p "$ENK_HOME/var/lock/controllerd.pid"
	echo

	echo -n "Stopping Enarksh spawner: "
	killproc -p "$ENK_HOME/var/lock/spawnerd.pid"
	echo

	echo -n "Stopping Enarksh logger: "
	killproc -p "$ENK_HOME/var/lock/loggerd.pid"
	echo

	rm -f "$LOCKFILE"
	echo
}

### main logic ###
case "$1" in
	start)
				start
				;;
	stop)
				stop
				;;
	status)
				status Enarksh
				;;
	restart|reload|condrestart)
				stop
				sleep 3
				start
				;;
	*)
				echo $"Usage: $0 {start|stop|restart|reload|status}"
				exit 1
esac
exit 0
